### ISSUE TITLE
Ako sam dobro razumeo.

### ISSUE THREAD

**Issue by Copser** [Copser/off_canvas_maps#1]
Ono sto si napisao na skypu, znaci ovako bi to recimo trebalo da se koncipira.

Napravim `click_event` za `mapu` koji ce da `trigger` `kontrollor` koji ucitava podatke u `nav-bar`.

`click` ----> `map/marker` ----> `kontroller` ----> `data_load_display` ----> `nav-bar`

Ja sam to koncipirao ovako, mislim to si ti inicirao. Krenuo sam od click funkcije za mapu ali sam malo tanak sa ovim `kontroller` `data` `load` `nav-bar`. 

Za `kontroller` sam mislio ovaj `checkbox` zato sto zelim da sklonim `haburger icon`, nece mi trebato, predpostavljam da to mogu da uradim?

**Comment by popara** [comment]
http://openlayers.org/en/v3.13.0/apidoc/ol.Feature.html#on

Preko ovog vezes eventove sa markera na kontroller,  cek da instaliram ovo pa cu napisati ovo da ti radi :)

**Comment by Copser** [comment]
U odlican primer, hvala na ovome.  Sad cu malo da ga razradim.

Sada trebam da naparvim ceo template na ovaj click na kome ce biti nalepljeni ovi array, predostavljam da mogu da ga provucem kroz ovaj tvoj kod, znaci click i ipada template (kao ajax sto radi, nesto slicno,tj. isto),  i da mogu da sredjujem tempate kako god pozelim, malo cu da googlam.

Hvala Pope ucitelju. ;)
